// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import InitSetReducer from "../init_set_reducer";
import SetPersonaReducer from "../set_persona_reducer";
import SetPlaybackReducer from "../set_playback_reducer";
import SubmitRequestReducer from "../submit_request_reducer";
import UpdatePatternReducer from "../update_pattern_reducer";

export type InitSetParams = __Infer<typeof InitSetReducer>;
export type SetPersonaParams = __Infer<typeof SetPersonaReducer>;
export type SetPlaybackParams = __Infer<typeof SetPlaybackReducer>;
export type SubmitRequestParams = __Infer<typeof SubmitRequestReducer>;
export type UpdatePatternParams = __Infer<typeof UpdatePatternReducer>;

