"use strict";
// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
Object.defineProperty(exports, "__esModule", { value: true });
/* eslint-disable */
/* tslint:disable */
const spacetimedb_1 = require("spacetimedb");
exports.default = spacetimedb_1.t.row({
    id: spacetimedb_1.t.u32().primaryKey(),
    currentCode: spacetimedb_1.t.string().name("current_code"),
    currentVibe: spacetimedb_1.t.string().name("current_vibe"),
    currentPersona: spacetimedb_1.t.string().name("current_persona"),
    cpm: spacetimedb_1.t.u32(),
    playbackActive: spacetimedb_1.t.bool().name("playback_active"),
    lastUpdatedAt: spacetimedb_1.t.timestamp().name("last_updated_at"),
});
