// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  currentCode: __t.string().name("current_code"),
  currentVibe: __t.string().name("current_vibe"),
  currentPersona: __t.string().name("current_persona"),
  cpm: __t.u32(),
  playbackActive: __t.bool().name("playback_active"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
