"use strict";
// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.DbConnection = exports.DbConnectionBuilder = exports.SubscriptionBuilder = exports.reducers = exports.tables = void 0;
// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).
/* eslint-disable */
/* tslint:disable */
const spacetimedb_1 = require("spacetimedb");
// Import all reducer arg schemas
const init_set_reducer_1 = __importDefault(require("./init_set_reducer"));
const set_persona_reducer_1 = __importDefault(require("./set_persona_reducer"));
const set_playback_reducer_1 = __importDefault(require("./set_playback_reducer"));
const submit_request_reducer_1 = __importDefault(require("./submit_request_reducer"));
const update_pattern_reducer_1 = __importDefault(require("./update_pattern_reducer"));
// Import all procedure arg schemas
// Import all table schema definitions
const dj_persona_table_1 = __importDefault(require("./dj_persona_table"));
const dj_set_table_1 = __importDefault(require("./dj_set_table"));
const music_request_table_1 = __importDefault(require("./music_request_table"));
/** Type-only namespace exports for generated type groups. */
/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = (0, spacetimedb_1.schema)({
    dj_persona: (0, spacetimedb_1.table)({
        name: 'dj_persona',
        indexes: [
            { name: 'name', algorithm: 'btree', columns: [
                    'name',
                ] },
        ],
        constraints: [
            { name: 'dj_persona_name_key', constraint: 'unique', columns: ['name'] },
        ],
    }, dj_persona_table_1.default),
    dj_set: (0, spacetimedb_1.table)({
        name: 'dj_set',
        indexes: [
            { name: 'id', algorithm: 'btree', columns: [
                    'id',
                ] },
        ],
        constraints: [
            { name: 'dj_set_id_key', constraint: 'unique', columns: ['id'] },
        ],
    }, dj_set_table_1.default),
    music_request: (0, spacetimedb_1.table)({
        name: 'music_request',
        indexes: [
            { name: 'id', algorithm: 'btree', columns: [
                    'id',
                ] },
        ],
        constraints: [
            { name: 'music_request_id_key', constraint: 'unique', columns: ['id'] },
        ],
    }, music_request_table_1.default),
});
/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = (0, spacetimedb_1.reducers)((0, spacetimedb_1.reducerSchema)("init_set", init_set_reducer_1.default), (0, spacetimedb_1.reducerSchema)("set_persona", set_persona_reducer_1.default), (0, spacetimedb_1.reducerSchema)("set_playback", set_playback_reducer_1.default), (0, spacetimedb_1.reducerSchema)("submit_request", submit_request_reducer_1.default), (0, spacetimedb_1.reducerSchema)("update_pattern", update_pattern_reducer_1.default));
/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = (0, spacetimedb_1.procedures)();
/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
    versionInfo: {
        cliVersion: "2.0.2",
    },
    tables: tablesSchema.schemaType.tables,
    reducers: reducersSchema.reducersType.reducers,
    ...proceduresSchema,
};
/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
exports.tables = (0, spacetimedb_1.makeQueryBuilder)(tablesSchema.schemaType);
/** The reducers available in this remote SpacetimeDB module. */
exports.reducers = (0, spacetimedb_1.convertToAccessorMap)(reducersSchema.reducersType.reducers);
/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
class SubscriptionBuilder extends spacetimedb_1.SubscriptionBuilderImpl {
}
exports.SubscriptionBuilder = SubscriptionBuilder;
/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
class DbConnectionBuilder extends spacetimedb_1.DbConnectionBuilder {
}
exports.DbConnectionBuilder = DbConnectionBuilder;
/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
class DbConnection extends spacetimedb_1.DbConnectionImpl {
    /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
    static builder = () => {
        return new DbConnectionBuilder(REMOTE_MODULE, (config) => new DbConnection(config));
    };
    /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
    subscriptionBuilder = () => {
        return new SubscriptionBuilder(this);
    };
}
exports.DbConnection = DbConnection;
