"use strict";
// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
Object.defineProperty(exports, "__esModule", { value: true });
/* eslint-disable */
/* tslint:disable */
const spacetimedb_1 = require("spacetimedb");
exports.default = spacetimedb_1.t.row({
    id: spacetimedb_1.t.u64().primaryKey(),
    sender: spacetimedb_1.t.identity(),
    text: spacetimedb_1.t.string(),
    priority: spacetimedb_1.t.string(),
    status: spacetimedb_1.t.string(),
    createdAt: spacetimedb_1.t.timestamp().name("created_at"),
});
