// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DjPersona = __t.object("DjPersona", {
  name: __t.string(),
  promptOverride: __t.string(),
  description: __t.string(),
});
export type DjPersona = __Infer<typeof DjPersona>;

export const DjSet = __t.object("DjSet", {
  id: __t.u32(),
  currentCode: __t.string(),
  currentVibe: __t.string(),
  currentPersona: __t.string(),
  cpm: __t.u32(),
  playbackActive: __t.bool(),
  lastUpdatedAt: __t.timestamp(),
});
export type DjSet = __Infer<typeof DjSet>;

export const MusicRequest = __t.object("MusicRequest", {
  id: __t.u64(),
  sender: __t.identity(),
  text: __t.string(),
  priority: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type MusicRequest = __Infer<typeof MusicRequest>;

