"use strict";
// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
Object.defineProperty(exports, "__esModule", { value: true });
/* eslint-disable */
/* tslint:disable */
const spacetimedb_1 = require("spacetimedb");
exports.default = {
    code: spacetimedb_1.t.string(),
    vibe: spacetimedb_1.t.string(),
};
